name: Test
on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: yarn install
      - name: Prettier
        run: yarn run prettier -w
      - name: ESLint
        run: yarn run eslint
      - name: Build
        run: yarn run build
      - name: Extract branch name
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Commit
        run: |
         git add -A
         git commit -m "GhActions[test] - Update files
         git push -u origin ${{ steps.extract_branch.outputs.branch }}